In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

F:\Anoconda\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)

In [4]:
df=pd.read_csv("./googleplaystore.csv",usecols=(0,1,2,3,4,5,6))

In [6]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free

In [7]:
df.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [11]:
#app需唯一
df[df.duplicated()]

,App,Category,Rating,Reviews,Size,Installs,Type
229,Quick PDF Scanner + OCR FREE,BUSINESS,4.2,80805,Varies with device,"5,000,000+",Free
236,Box,BUSINESS,4.2,159872,Varies with device,"10,000,000+",Free
239,Google My Business,BUSINESS,4.4,70991,Varies with device,"5,000,000+",Free
256,ZOOM Cloud Meetings,BUSINESS,4.4,31614,37M,"10,000,000+",Free
261,join.me - Simple Meetings,BUSINESS,4.0,6989,Varies with device,"1,000,000+",Free
265,Box,BUSINESS,4.2,159872,Varies with device,"10,000,000+",Free
266,Zenefits,BUSINESS,4.2,296,14M,"50,000+",Free
267,Google Ads,BUSINESS,4.3,29313,20M,"5,000,000+",Free
268,Google My Business,BUSINESS,4.4,70991,Varies with device,"5,000,000+",Free
269,Slack,BUSINESS,4.4,51507,Varies with device,"5,000,000+",Free
270,FreshBooks Classic,BUSINESS,4.1,1802,26M,"100,000+",Free
271,Insightly CRM,BUSINESS,3.8,1383,51M,"100,000+",Free
272,QuickBooks Accounting: Invoicing & Expenses,BUSINESS,4.3,23175,41M,"1,000,000+",Free
273,HipChat - Chat Built for Teams,BUSINESS,3.8,5868,20M,"500,000+",Free
274,Xero Accounting Software,BUSINESS,3.5,2111,Varies with device,"100,000+",Free
275,"MailChimp - Email, Marketing Automation",BUSINESS,4.1,5448,12M,"500,000+",Free
276,Crew - Free Messaging and Scheduling,BUSINESS,4.6,4159,48M,"500,000+",Free
277,Asana: organize team projects,BUSINESS,4.3,20815,10M,"1,000,000+",Free
278,Google Analytics,BUSINESS,4.5,78662,22M,"1,000,000+",Free
279,AdWords Express,BUSINESS,4.1,7149,11M,"1,000,000+",Free
280,Accounting App - Zoho Books,BUSINESS,4.5,3079,8.5M,"100,000+",Free
281,Invoice & Time Tracking - Zoho,BUSINESS,4.6,5800,8.6M,"100,000+",Free
282,join.me - Simple Meetings,BUSINESS,4.0,6989,Varies with device,"1,000,000+",Free
283,Invoice 2go — Professional Invoices and Estimates,BUSINESS,4.2,16422,28M,"1,000,000+",Free
284,SignEasy | Sign and Fill PDF and other Documents,BUSINESS,4.3,8978,Varies with device,"1,000,000+",Free
286,Genius Scan - PDF Scanner,BUSINESS,4.4,42492,Varies with device,"1,000,000+",Free
287,Tiny Scanner - PDF Scanner App,BUSINESS,4.7,286897,39M,"10,000,000+",Free
288,Fast Scanner : Free PDF Scan,BUSINESS,4.5,103755,14M,"10,000,000+",Free
289,Mobile Doc Scanner (MDScan) Lite,BUSINESS,4.2,46505,19M,"1,000,000+",Free
290,TurboScan: scan documents and receipts in PDF,BUSINESS,4.7,11442,6.8M,"100,000+",Paid
...,...,...,...,...,...,...,...
4441,O-Star,DATING,4.4,59,38M,"5,000+",Free
5147,Maricopa AH,MEDICAL,NaN,0,29M,100+,Free
5537,Houzz Interior Design Ideas,HOUSE_AND_HOME,4.6,353813,Varies with device,"10,000,000+",Free
5958,Anthem BC Anywhere,MEDICAL,2.6,496,24M,"100,000+",Free
5989,PMHNP-BC Pocket Prep,MEDICAL,4.4,112,13M,"1,000+",Free
6584,iBP Blood Pressure,MEDICAL,4.4,578,704k,"10,000+",Paid
6585,Blood Pressure,MEDICAL,4.2,33033,7.4M,"5,000,000+",Free
6590,Blood Pressure(BP) Diary,MEDICAL,3.7,3596,8.4M,"1,000,000+",Free
6593,BP Journal - Blood Pressure Diary,MEDICAL,5.0,6,26M,"1,000+",Free
6594,Blood Pressure Monitor,MEDICAL,4.3,17,6.0M,"10,000+",Free
6595,Blood Pressure Companion,MEDICAL,4.2,178,4.8M,"1,000+",Paid
6598,Free Blood Pressure,MEDICAL,NaN,7,5.7M,"5,000+",Free
6911,Beautiful Widgets Pro,PERSONALIZATION,4.2,97890,14M,"1,000,000+",Paid
7030,Elmo Calls by Sesame Street,FAMILY,3.9,6903,25M,"1,000,000+",Free
7035,420 BZ Budeze Delivery,MEDICAL,5.0,2,11M,100+,Free
7628,Brit + Co,LIFESTYLE,3.9,987,4.5M,"10,000+",Free
7885,CT Scan Cross Sectional Anatomy,MEDICAL,4.3,10,46M,100+,Free
8628,Google Docs,PRODUCTIVITY,4.3,815974,Varies with device,"100,000,000+",Free
8630,"Any.do: To-do list, Calendar, Reminders & Planner",PRODUCTIVITY,4.5,298854,Varies with device,"10,000,000+",Free
8632,Notepad & To do list,PRODUCTIVITY,4.3,226295,4.2M,"10,000,000+",Free
8635,"Polaris Office - Word, Docs, Sheets, Slide, PDF",PRODUCTIVITY,4.3,549900,60M,"10,000,000+",Free
8636,Google Keep,PRODUCTIVITY,4.4,691474,Varies with device,"100,000,000+",Free
8639,Do It Later: Tasks & To-Dos,PRODUCTIVITY,4.5,123412,Varies with device,"50,000,000+",Free
8642,To-Do Calendar Planner,PRODUCTIVITY,4.2,30291,Varies with device,"1,000,000+",Free
8643,Wunderlist: To-Do List & Tasks,PRODUCTIVITY,4.6,404610,Varies with device,"10,000,000+",Free
8654,"TickTick: To Do List with Reminder, Day Planner",PRODUCTIVITY,4.6,25370,Varies with device,"1,000,000+",Free
8658,ColorNote Notepad Notes,PRODUCTIVITY,4.6,2401017,Varies with device,"100,000,000+",Free
10049,Airway Ex - Intubate. Anesthetize. Train.,MEDICAL,4.3,123,86M,"10,000+",Free
10473,osmino Wi-Fi: free WiFi,TOOLS,4.2,134203,4.1M,"10,000,000+",Free
10768,AAFP,MEDICAL,3.8,63,24M,"10,000+",Free

In [13]:
df["Category"].value_counts(dropna=False)

FAMILY                 1972
GAME                   1144
TOOLS                   843
MEDICAL                 463
BUSINESS                460
PRODUCTIVITY            424
PERSONALIZATION         392
COMMUNICATION           387
SPORTS                  384
LIFESTYLE               382
FINANCE                 366
HEALTH_AND_FITNESS      341
PHOTOGRAPHY             335
SOCIAL                  295
NEWS_AND_MAGAZINES      283
SHOPPING                260
TRAVEL_AND_LOCAL        258
DATING                  234
BOOKS_AND_REFERENCE     231
VIDEO_PLAYERS           175
EDUCATION               156
ENTERTAINMENT           149
MAPS_AND_NAVIGATION     137
FOOD_AND_DRINK          127
HOUSE_AND_HOME           88
AUTO_AND_VEHICLES        85
LIBRARIES_AND_DEMO       85
WEATHER                  82
ART_AND_DESIGN           65
EVENTS                   64
COMICS                   60
PARENTING                60
BEAUTY                   53
1.9                       1
Name: Category, dtype: int64

In [16]:
df[df["Category"]=="1.9"]

,App,Category,Rating,Reviews,Size,Installs,Type
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0

In [17]:
df.drop(index=10472,inplace=True)

In [18]:
df["Rating"].value_counts(dropna=False)

NaN    1474
4.4    1109
4.3    1076
4.5    1038
4.2     952
4.6     823
4.1     708
4.0     568
4.7     499
3.9     386
3.8     303
5.0     274
3.7     239
4.8     234
3.6     174
3.5     163
3.4     128
3.3     102
4.9      87
3.0      83
3.1      69
3.2      64
2.9      45
2.8      42
2.7      25
2.6      25
2.5      21
2.3      20
2.4      19
1.0      16
2.2      14
1.9      13
2.0      12
1.7       8
1.8       8
2.1       8
1.6       4
1.5       3
1.4       3
1.2       1
Name: Rating, dtype: int64

In [19]:
#填充Rating
df["Rating"].fillna(df["Rating"].mean(),inplace=True)

In [20]:
#填充成功
df["Rating"].value_counts(dropna=False)

4.191757    1474
4.400000    1109
4.300000    1076
4.500000    1038
4.200000     952
4.600000     823
4.100000     708
4.000000     568
4.700000     499
3.900000     386
3.800000     303
5.000000     274
3.700000     239
4.800000     234
3.600000     174
3.500000     163
3.400000     128
3.300000     102
4.900000      87
3.000000      83
3.100000      69
3.200000      64
2.900000      45
2.800000      42
2.700000      25
2.600000      25
2.500000      21
2.300000      20
2.400000      19
1.000000      16
2.200000      14
1.900000      13
2.000000      12
1.800000       8
1.700000       8
2.100000       8
1.600000       4
1.500000       3
1.400000       3
1.200000       1
Name: Rating, dtype: int64

In [23]:
#看review 数据 没有非数字
df[~df["Reviews"].str.isnumeric()]

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type]
Index: []

In [44]:
#看类型 并转化
df.info()
df["Reviews"]=df["Reviews"].astype("i8")

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10840 entries, 0 to 10840
Data columns (total 7 columns):
App         10840 non-null object
Category    10840 non-null object
Rating      10840 non-null float64
Reviews     10840 non-null object
Size        10840 non-null object
Installs    10840 non-null object
Type        10839 non-null object
dtypes: float64(1), object(6)
memory usage: 677.5+ KB

In [45]:
df.describe()

             Rating       Reviews
count  10840.000000  1.084000e+04
mean       4.191757  4.441529e+05
std        0.478907  2.927761e+06
min        1.000000  0.000000e+00
25%        4.100000  3.800000e+01
50%        4.200000  2.094000e+03
75%        4.500000  5.477550e+04
max        5.000000  7.815831e+07

In [48]:
#处理size
df["Size"]=df["Size"].str.replace("M","e+6")
df["Size"]=df["Size"].str.replace("k","e+3")
df["Size"]=df["Size"].str.replace("Varies with device","0")

In [52]:
df["Size"]=df["Size"].astype("f8")

In [54]:
df.describe()

             Rating       Reviews          Size
count  10840.000000  1.084000e+04  1.084000e+04
mean       4.191757  4.441529e+05  1.815209e+07
std        0.478907  2.927761e+06  2.217061e+07
min        1.000000  0.000000e+00  0.000000e+00
25%        4.100000  3.800000e+01  2.600000e+06
50%        4.200000  2.094000e+03  9.200000e+06
75%        4.500000  5.477550e+04  2.600000e+07
max        5.000000  7.815831e+07  1.000000e+08

In [58]:
#清洗installs
df["Installs"]=df["Installs"].str.replace("+","")
df["Installs"]=df["Installs"].str.replace(",","")
df["Installs"]=df["Installs"].astype("i8")

In [59]:
df.describe()

             Rating       Reviews          Size      Installs
count  10840.000000  1.084000e+04  1.084000e+04  1.084000e+04
mean       4.191757  4.441529e+05  1.815209e+07  1.546434e+07
std        0.478907  2.927761e+06  2.217061e+07  8.502936e+07
min        1.000000  0.000000e+00  0.000000e+00  0.000000e+00
25%        4.100000  3.800000e+01  2.600000e+06  1.000000e+03
50%        4.200000  2.094000e+03  9.200000e+06  1.000000e+05
75%        4.500000  5.477550e+04  2.600000e+07  5.000000e+06
max        5.000000  7.815831e+07  1.000000e+08  1.000000e+09

In [60]:
#处理type
df["Type"].value_counts(dropna=False)

Free    10039
Paid      800
NaN         1
Name: Type, dtype: int64

In [64]:
df[df["Type"].isnull()]

,App,Category,Rating,Reviews,Size,Installs,Type
9148,Command & Conquer: Rivals,FAMILY,4.191757,0,0.0,0,NaN

In [69]:
df.drop(index=9148,inplace=True)

In [70]:
#删除重复的App
df.drop_duplicates("App",inplace=True)

# 分析

In [72]:
#看不同分类的App个数
df.groupby("Category").count().sort_values("App",ascending=False)

                      App  Rating  Reviews  Size  Installs  Type
Category
FAMILY               1831    1831     1831  1831      1831  1831
GAME                  959     959      959   959       959   959
TOOLS                 827     827      827   827       827   827
BUSINESS              420     420      420   420       420   420
MEDICAL               395     395      395   395       395   395
PERSONALIZATION       376     376      376   376       376   376
PRODUCTIVITY          374     374      374   374       374   374
LIFESTYLE             369     369      369   369       369   369
FINANCE               345     345      345   345       345   345
SPORTS                325     325      325   325       325   325
COMMUNICATION         315     315      315   315       315   315
HEALTH_AND_FITNESS    288     288      288   288       288   288
PHOTOGRAPHY           281     281      281   281       281   281
NEWS_AND_MAGAZINES    254     254      254   254       254   254
SOCIAL                239     239      239   239       239   239
BOOKS_AND_REFERENCE   222     222      222   222       222   222
TRAVEL_AND_LOCAL      219     219      219   219       219   219
SHOPPING              202     202      202   202       202   202
DATING                171     171      171   171       171   171
VIDEO_PLAYERS         163     163      163   163       163   163
MAPS_AND_NAVIGATION   131     131      131   131       131   131
EDUCATION             119     119      119   119       119   119
FOOD_AND_DRINK        112     112      112   112       112   112
ENTERTAINMENT         102     102      102   102       102   102
AUTO_AND_VEHICLES      85      85       85    85        85    85
LIBRARIES_AND_DEMO     84      84       84    84        84    84
WEATHER                79      79       79    79        79    79
HOUSE_AND_HOME         74      74       74    74        74    74
EVENTS                 64      64       64    64        64    64
ART_AND_DESIGN         64      64       64    64        64    64
PARENTING              60      60       60    60        60    60
COMICS                 56      56       56    56        56    56
BEAUTY                 53      53       53    53        53    53

In [73]:
#看App受欢迎程度
df.groupby("Category").mean().sort_values("Installs",ascending=False)

                       Rating        Reviews          Size      Installs
Category
COMMUNICATION        4.134647  907337.676190  8.686978e+06  3.504215e+07
VIDEO_PLAYERS        4.058137  414015.754601  1.230479e+07  2.409143e+07
SOCIAL               4.238926  953672.807531  1.264014e+07  2.296179e+07
ENTERTAINMENT        4.135294  340810.294118  1.445882e+07  2.072216e+07
PHOTOGRAPHY          4.159614  374915.551601  1.237682e+07  1.654501e+07
PRODUCTIVITY         4.185022  148638.098930  9.603393e+06  1.548955e+07
GAME                 4.244643  648903.763295  3.811215e+07  1.447229e+07
TRAVEL_AND_LOCAL     4.087380  122464.570776  1.912038e+07  1.321866e+07
TOOLS                4.059615  277335.644498  7.763306e+06  9.675661e+06
NEWS_AND_MAGAZINES   4.135385   91063.889764  9.868142e+06  9.327629e+06
BOOKS_AND_REFERENCE  4.308393   75321.234234  1.147807e+07  7.504367e+06
SHOPPING             4.225835  220553.118812  1.288397e+07  6.932420e+06
WEATHER              4.238510  155634.987342  8.988380e+06  4.570893e+06
PERSONALIZATION      4.303077  142401.808511  1.047831e+07  4.075784e+06
HEALTH_AND_FITNESS   4.235199   74171.371528  1.665060e+07  3.972300e+06
MAPS_AND_NAVIGATION  4.051854  135337.007634  1.336938e+07  3.841846e+06
SPORTS               4.211275  108765.578462  2.109733e+07  3.373768e+06
EDUCATION            4.362956  112303.764706  1.425279e+07  2.965983e+06
FAMILY               4.181137   78550.239214  2.562887e+07  2.418319e+06
FOOD_AND_DRINK       4.175461   56473.464286  1.610268e+07  1.891060e+06
ART_AND_DESIGN       4.349614   22175.046875  1.198438e+07  1.786533e+06
BUSINESS             4.133347   23548.202381  1.241444e+07  1.659916e+06
LIFESTYLE            4.111489   32066.859079  1.343686e+07  1.365375e+06
FINANCE              4.125060   36701.756522  1.505238e+07  1.319851e+06
HOUSE_AND_HOME       4.156771   26079.013514  1.338049e+07  1.313682e+06
DATING               4.018100   21190.315789  1.456209e+07  8.241293e+05
COMICS               4.181848   41822.696429  1.207059e+07  8.032348e+05
LIBRARIES_AND_DEMO   4.181371   10795.607143  1.022421e+07  6.309037e+05
AUTO_AND_VEHICLES    4.190601   13690.188235  1.767984e+07  6.250613e+05
PARENTING            4.281960   15972.183333  2.026167e+07  5.253518e+05
BEAUTY               4.260553    7476.226415  1.223396e+07  5.131519e+05
EVENTS               4.363178    2515.906250  1.243647e+07  2.495806e+05
MEDICAL              4.173252    2994.863291  1.787772e+07  9.669159e+04

In [74]:
#看哪类App口碑好
df.groupby("Category").mean().sort_values("Reviews",ascending=False)

                       Rating        Reviews          Size      Installs
Category
SOCIAL               4.238926  953672.807531  1.264014e+07  2.296179e+07
COMMUNICATION        4.134647  907337.676190  8.686978e+06  3.504215e+07
GAME                 4.244643  648903.763295  3.811215e+07  1.447229e+07
VIDEO_PLAYERS        4.058137  414015.754601  1.230479e+07  2.409143e+07
PHOTOGRAPHY          4.159614  374915.551601  1.237682e+07  1.654501e+07
ENTERTAINMENT        4.135294  340810.294118  1.445882e+07  2.072216e+07
TOOLS                4.059615  277335.644498  7.763306e+06  9.675661e+06
SHOPPING             4.225835  220553.118812  1.288397e+07  6.932420e+06
WEATHER              4.238510  155634.987342  8.988380e+06  4.570893e+06
PRODUCTIVITY         4.185022  148638.098930  9.603393e+06  1.548955e+07
PERSONALIZATION      4.303077  142401.808511  1.047831e+07  4.075784e+06
MAPS_AND_NAVIGATION  4.051854  135337.007634  1.336938e+07  3.841846e+06
TRAVEL_AND_LOCAL     4.087380  122464.570776  1.912038e+07  1.321866e+07
EDUCATION            4.362956  112303.764706  1.425279e+07  2.965983e+06
SPORTS               4.211275  108765.578462  2.109733e+07  3.373768e+06
NEWS_AND_MAGAZINES   4.135385   91063.889764  9.868142e+06  9.327629e+06
FAMILY               4.181137   78550.239214  2.562887e+07  2.418319e+06
BOOKS_AND_REFERENCE  4.308393   75321.234234  1.147807e+07  7.504367e+06
HEALTH_AND_FITNESS   4.235199   74171.371528  1.665060e+07  3.972300e+06
FOOD_AND_DRINK       4.175461   56473.464286  1.610268e+07  1.891060e+06
COMICS               4.181848   41822.696429  1.207059e+07  8.032348e+05
FINANCE              4.125060   36701.756522  1.505238e+07  1.319851e+06
LIFESTYLE            4.111489   32066.859079  1.343686e+07  1.365375e+06
HOUSE_AND_HOME       4.156771   26079.013514  1.338049e+07  1.313682e+06
BUSINESS             4.133347   23548.202381  1.241444e+07  1.659916e+06
ART_AND_DESIGN       4.349614   22175.046875  1.198438e+07  1.786533e+06
DATING               4.018100   21190.315789  1.456209e+07  8.241293e+05
PARENTING            4.281960   15972.183333  2.026167e+07  5.253518e+05
AUTO_AND_VEHICLES    4.190601   13690.188235  1.767984e+07  6.250613e+05
LIBRARIES_AND_DEMO   4.181371   10795.607143  1.022421e+07  6.309037e+05
BEAUTY               4.260553    7476.226415  1.223396e+07  5.131519e+05
MEDICAL              4.173252    2994.863291  1.787772e+07  9.669159e+04
EVENTS               4.363178    2515.906250  1.243647e+07  2.495806e+05

In [76]:
df.groupby("Type").count()

       App  Category  Rating  Reviews  Size  Installs
Type
Free  8902      8902    8902     8902  8902      8902
Paid   756       756     756      756   756       756

In [77]:
df.groupby(["Type","Category"]).count()

                           App  Rating  Reviews  Size  Installs
Type Category
Free ART_AND_DESIGN         61      61       61    61        61
     AUTO_AND_VEHICLES      82      82       82    82        82
     BEAUTY                 53      53       53    53        53
     BOOKS_AND_REFERENCE   194     194      194   194       194
     BUSINESS              408     408      408   408       408
     COMICS                 56      56       56    56        56
     COMMUNICATION         288     288      288   288       288
     DATING                165     165      165   165       165
     EDUCATION             115     115      115   115       115
     ENTERTAINMENT         100     100      100   100       100
     EVENTS                 63      63       63    63        63
     FAMILY               1648    1648     1648  1648      1648
     FINANCE               328     328      328   328       328
     FOOD_AND_DRINK        110     110      110   110       110
     GAME                  877     877      877   877       877
     HEALTH_AND_FITNESS    273     273      273   273       273
     HOUSE_AND_HOME         74      74       74    74        74
     LIBRARIES_AND_DEMO     83      83       83    83        83
     LIFESTYLE             350     350      350   350       350
     MAPS_AND_NAVIGATION   126     126      126   126       126
     MEDICAL               312     312      312   312       312
     NEWS_AND_MAGAZINES    252     252      252   252       252
     PARENTING              58      58       58    58        58
     PERSONALIZATION       295     295      295   295       295
     PHOTOGRAPHY           262     262      262   262       262
     PRODUCTIVITY          346     346      346   346       346
     SHOPPING              200     200      200   200       200
     SOCIAL                236     236      236   236       236
     SPORTS                301     301      301   301       301
     TOOLS                 749     749      749   749       749
...                        ...     ...      ...   ...       ...
Paid ART_AND_DESIGN          3       3        3     3         3
     AUTO_AND_VEHICLES       3       3        3     3         3
     BOOKS_AND_REFERENCE    28      28       28    28        28
     BUSINESS               12      12       12    12        12
     COMMUNICATION          27      27       27    27        27
     DATING                  6       6        6     6         6
     EDUCATION               4       4        4     4         4
     ENTERTAINMENT           2       2        2     2         2
     EVENTS                  1       1        1     1         1
     FAMILY                183     183      183   183       183
     FINANCE                17      17       17    17        17
     FOOD_AND_DRINK          2       2        2     2         2
     GAME                   82      82       82    82        82
     HEALTH_AND_FITNESS     15      15       15    15        15
     LIBRARIES_AND_DEMO      1       1        1     1         1
     LIFESTYLE              19      19       19    19        19
     MAPS_AND_NAVIGATION     5       5        5     5         5
     MEDICAL                83      83       83    83        83
     NEWS_AND_MAGAZINES      2       2        2     2         2
     PARENTING               2       2        2     2         2
     PERSONALIZATION        81      81       81    81        81
     PHOTOGRAPHY            19      19       19    19        19
     PRODUCTIVITY           28      28       28    28        28
     SHOPPING                2       2        2     2         2
     SOCIAL                  3       3        3     3         3
     SPORTS                 24      24       24    24        24
     TOOLS                  78      78       78    78        78
     TRAVEL_AND_LOCAL       12      12       12    12        12
     VIDEO_PLAYERS           4       4        4     4         4
     WEATHER                 8       8        8     8         8

[63 rows x 5 columns]

In [79]:
#查看相关性
df.corr()

            Rating   Reviews      Size  Installs
Rating    1.000000  0.054337  0.034819  0.039245
Reviews   0.054337  1.000000  0.037870  0.625164
Size      0.034819  0.037870  1.000000 -0.007489
Installs  0.039245  0.625164 -0.007489  1.000000